server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/position.yml

clients:
  - url: http://172.20.0.4:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend-logs
    static_configs:
      - targets:
         - localhost
        labels:
          job: backend
          __path__: /var/lib/docker/containers/*/*.log
